# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUIMXKDYa.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_ComingSoon(object):
    def setupUi(self, ComingSoon):
        if ComingSoon.objectName():
            ComingSoon.setObjectName(u"ComingSoon")
        ComingSoon.resize(1230, 869)
        self.actionGrayscale = QAction(ComingSoon)
        self.actionGrayscale.setObjectName(u"actionGrayscale")
        self.actionBiner = QAction(ComingSoon)
        self.actionBiner.setObjectName(u"actionBiner")
        self.actionNegative = QAction(ComingSoon)
        self.actionNegative.setObjectName(u"actionNegative")
        self.actionCoba = QAction(ComingSoon)
        self.actionCoba.setObjectName(u"actionCoba")
        self.actionHistogram_Grayscale = QAction(ComingSoon)
        self.actionHistogram_Grayscale.setObjectName(u"actionHistogram_Grayscale")
        self.actionHistogram_RGB = QAction(ComingSoon)
        self.actionHistogram_RGB.setObjectName(u"actionHistogram_RGB")
        self.actionHistogram_Equalization = QAction(ComingSoon)
        self.actionHistogram_Equalization.setObjectName(u"actionHistogram_Equalization")
        self.actionSimple_Contrast = QAction(ComingSoon)
        self.actionSimple_Contrast.setObjectName(u"actionSimple_Contrast")
        self.actionContrast_Stretching = QAction(ComingSoon)
        self.actionContrast_Stretching.setObjectName(u"actionContrast_Stretching")
        self.actionGamma_Correction = QAction(ComingSoon)
        self.actionGamma_Correction.setObjectName(u"actionGamma_Correction")
        self.actionKonvolusi = QAction(ComingSoon)
        self.actionKonvolusi.setObjectName(u"actionKonvolusi")
        self.actionMean = QAction(ComingSoon)
        self.actionMean.setObjectName(u"actionMean")
        self.actionGaussian = QAction(ComingSoon)
        self.actionGaussian.setObjectName(u"actionGaussian")
        self.actionMean_Filter = QAction(ComingSoon)
        self.actionMean_Filter.setObjectName(u"actionMean_Filter")
        self.actionGaussian_Filter = QAction(ComingSoon)
        self.actionGaussian_Filter.setObjectName(u"actionGaussian_Filter")
        self.actionMedian_Filter = QAction(ComingSoon)
        self.actionMedian_Filter.setObjectName(u"actionMedian_Filter")
        self.actionDFT_Smoothing = QAction(ComingSoon)
        self.actionDFT_Smoothing.setObjectName(u"actionDFT_Smoothing")
        self.actionBilateral_Filter = QAction(ComingSoon)
        self.actionBilateral_Filter.setObjectName(u"actionBilateral_Filter")
        self.actionTranslasi = QAction(ComingSoon)
        self.actionTranslasi.setObjectName(u"actionTranslasi")
        self.actionTranspose = QAction(ComingSoon)
        self.actionTranspose.setObjectName(u"actionTranspose")
        self.actionCrop_Image = QAction(ComingSoon)
        self.actionCrop_Image.setObjectName(u"actionCrop_Image")
        self.action_min90d = QAction(ComingSoon)
        self.action_min90d.setObjectName(u"action_min90d")
        self.action_min45d = QAction(ComingSoon)
        self.action_min45d.setObjectName(u"action_min45d")
        self.action45d = QAction(ComingSoon)
        self.action45d.setObjectName(u"action45d")
        self.action90d = QAction(ComingSoon)
        self.action90d.setObjectName(u"action90d")
        self.action180d = QAction(ComingSoon)
        self.action180d.setObjectName(u"action180d")
        self.action2X = QAction(ComingSoon)
        self.action2X.setObjectName(u"action2X")
        self.action3X = QAction(ComingSoon)
        self.action3X.setObjectName(u"action3X")
        self.action4X = QAction(ComingSoon)
        self.action4X.setObjectName(u"action4X")
        self.actionQuarter = QAction(ComingSoon)
        self.actionQuarter.setObjectName(u"actionQuarter")
        self.actionHalf = QAction(ComingSoon)
        self.actionHalf.setObjectName(u"actionHalf")
        self.actionThree_Quarter = QAction(ComingSoon)
        self.actionThree_Quarter.setObjectName(u"actionThree_Quarter")
        self.action360p = QAction(ComingSoon)
        self.action360p.setObjectName(u"action360p")
        self.action480p = QAction(ComingSoon)
        self.action480p.setObjectName(u"action480p")
        self.action720p = QAction(ComingSoon)
        self.action720p.setObjectName(u"action720p")
        self.action1080p = QAction(ComingSoon)
        self.action1080p.setObjectName(u"action1080p")
        self.actionplusmin = QAction(ComingSoon)
        self.actionplusmin.setObjectName(u"actionplusmin")
        self.actionkalibagi = QAction(ComingSoon)
        self.actionkalibagi.setObjectName(u"actionkalibagi")
        self.actionAND = QAction(ComingSoon)
        self.actionAND.setObjectName(u"actionAND")
        self.actionOR = QAction(ComingSoon)
        self.actionOR.setObjectName(u"actionOR")
        self.actionXOR = QAction(ComingSoon)
        self.actionXOR.setObjectName(u"actionXOR")
        self.actionPre_processing = QAction(ComingSoon)
        self.actionPre_processing.setObjectName(u"actionPre_processing")
        self.actionOperasi_Pencerahan = QAction(ComingSoon)
        self.actionOperasi_Pencerahan.setObjectName(u"actionOperasi_Pencerahan")
        self.centralwidget = QWidget(ComingSoon)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 1231, 851))
        self.widget.setStyleSheet(u"background-color: rgb(45, 48, 55);")
        self.widget_2 = QWidget(self.widget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(0, 0, 1231, 111))
        self.widget_2.setStyleSheet(u"background-color: #E7B18E;")
        self.label_3 = QLabel(self.widget_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(310, 10, 611, 101))
        font = QFont()
        font.setFamily(u"Casta Thin")
        font.setPointSize(72)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(Qt.LeftToRight)
        self.label_3.setStyleSheet(u"color: E7B18E;")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.btn_close = QPushButton(self.widget_2)
        self.btn_close.setObjectName(u"btn_close")
        self.btn_close.setGeometry(QRect(1130, 20, 18, 18))
        self.btn_close.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_close.setStyleSheet(u"background: #FF605C;\n"
"border-radius: 9%;")
        self.btn_minimize = QPushButton(self.widget_2)
        self.btn_minimize.setObjectName(u"btn_minimize")
        self.btn_minimize.setGeometry(QRect(1160, 20, 18, 18))
        self.btn_minimize.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_minimize.setStyleSheet(u"background: #FFBD44;\n"
"border-radius: 9%;")
        self.btn_gtw = QPushButton(self.widget_2)
        self.btn_gtw.setObjectName(u"btn_gtw")
        self.btn_gtw.setGeometry(QRect(1190, 20, 18, 18))
        self.btn_gtw.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_gtw.setStyleSheet(u"background: #00CA4E;\n"
"border-radius: 9%;")
        self.label_back = QLabel(self.widget_2)
        self.label_back.setObjectName(u"label_back")
        self.label_back.setGeometry(QRect(0, 20, 151, 71))
        self.label_back.setCursor(QCursor(Qt.PointingHandCursor))
        self.label_back.setPixmap(QPixmap(u"Ihome.png"))
        self.label_credits = QLabel(self.widget)
        self.label_credits.setObjectName(u"label_credits")
        self.label_credits.setGeometry(QRect(460, 810, 761, 31))
        font1 = QFont()
        font1.setFamily(u"Gramatika-Medium")
        font1.setPointSize(10)
        self.label_credits.setFont(font1)
        self.label_credits.setStyleSheet(u"color: rgb(110, 117, 134);")
        self.label_credits.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(230, 360, 761, 101))
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(Qt.LeftToRight)
        self.label_4.setStyleSheet(u"color: #E7B18E;")
        self.label_4.setAlignment(Qt.AlignCenter)
        ComingSoon.setCentralWidget(self.centralwidget)

        self.retranslateUi(ComingSoon)

        QMetaObject.connectSlotsByName(ComingSoon)
    # setupUi

    def retranslateUi(self, ComingSoon):
        ComingSoon.setWindowTitle(QCoreApplication.translate("ComingSoon", u"MainWindow", None))
        self.actionGrayscale.setText(QCoreApplication.translate("ComingSoon", u"Grayscale", None))
        self.actionBiner.setText(QCoreApplication.translate("ComingSoon", u"Biner", None))
        self.actionNegative.setText(QCoreApplication.translate("ComingSoon", u"Negative", None))
        self.actionCoba.setText(QCoreApplication.translate("ComingSoon", u"Coba", None))
        self.actionHistogram_Grayscale.setText(QCoreApplication.translate("ComingSoon", u"Histogram Grayscale", None))
        self.actionHistogram_RGB.setText(QCoreApplication.translate("ComingSoon", u"Histogram RGB", None))
        self.actionHistogram_Equalization.setText(QCoreApplication.translate("ComingSoon", u"Histogram Equalization", None))
        self.actionSimple_Contrast.setText(QCoreApplication.translate("ComingSoon", u"Simple Contrast", None))
        self.actionContrast_Stretching.setText(QCoreApplication.translate("ComingSoon", u"Contrast Stretching", None))
        self.actionGamma_Correction.setText(QCoreApplication.translate("ComingSoon", u"Gamma Correction", None))
        self.actionKonvolusi.setText(QCoreApplication.translate("ComingSoon", u"Konvolusi", None))
        self.actionMean.setText(QCoreApplication.translate("ComingSoon", u"Mean", None))
        self.actionGaussian.setText(QCoreApplication.translate("ComingSoon", u"Gaussian", None))
        self.actionMean_Filter.setText(QCoreApplication.translate("ComingSoon", u"Mean Filter", None))
        self.actionGaussian_Filter.setText(QCoreApplication.translate("ComingSoon", u"Gaussian Filter", None))
        self.actionMedian_Filter.setText(QCoreApplication.translate("ComingSoon", u"Median Filter", None))
        self.actionDFT_Smoothing.setText(QCoreApplication.translate("ComingSoon", u"DFT Smoothing", None))
        self.actionBilateral_Filter.setText(QCoreApplication.translate("ComingSoon", u"Bilateral Filter", None))
        self.actionTranslasi.setText(QCoreApplication.translate("ComingSoon", u"Translasi", None))
        self.actionTranspose.setText(QCoreApplication.translate("ComingSoon", u"Transpose", None))
        self.actionCrop_Image.setText(QCoreApplication.translate("ComingSoon", u"Crop Image", None))
        self.action_min90d.setText(QCoreApplication.translate("ComingSoon", u"-90 Derajat", None))
        self.action_min45d.setText(QCoreApplication.translate("ComingSoon", u"-45 Derajat", None))
        self.action45d.setText(QCoreApplication.translate("ComingSoon", u"45 Derajat", None))
        self.action90d.setText(QCoreApplication.translate("ComingSoon", u"90 Derajat", None))
        self.action180d.setText(QCoreApplication.translate("ComingSoon", u"180 Derajat", None))
        self.action2X.setText(QCoreApplication.translate("ComingSoon", u"2X", None))
        self.action3X.setText(QCoreApplication.translate("ComingSoon", u"3X", None))
        self.action4X.setText(QCoreApplication.translate("ComingSoon", u"4X", None))
        self.actionQuarter.setText(QCoreApplication.translate("ComingSoon", u"1/4", None))
        self.actionHalf.setText(QCoreApplication.translate("ComingSoon", u"1/2", None))
        self.actionThree_Quarter.setText(QCoreApplication.translate("ComingSoon", u"3/4", None))
        self.action360p.setText(QCoreApplication.translate("ComingSoon", u"360p", None))
        self.action480p.setText(QCoreApplication.translate("ComingSoon", u"480p", None))
        self.action720p.setText(QCoreApplication.translate("ComingSoon", u"720p", None))
        self.action1080p.setText(QCoreApplication.translate("ComingSoon", u"1080p", None))
        self.actionplusmin.setText(QCoreApplication.translate("ComingSoon", u"Tambah dan Kurang", None))
        self.actionkalibagi.setText(QCoreApplication.translate("ComingSoon", u"Kali dan Bagi", None))
        self.actionAND.setText(QCoreApplication.translate("ComingSoon", u"AND", None))
        self.actionOR.setText(QCoreApplication.translate("ComingSoon", u"OR", None))
        self.actionXOR.setText(QCoreApplication.translate("ComingSoon", u"XOR", None))
        self.actionPre_processing.setText(QCoreApplication.translate("ComingSoon", u"Pre-processing", None))
        self.actionOperasi_Pencerahan.setText(QCoreApplication.translate("ComingSoon", u"Operasi Pencerahan", None))
        self.label_3.setText(QCoreApplication.translate("ComingSoon", u"Coming Soon", None))
        self.btn_close.setText("")
        self.btn_minimize.setText("")
        self.btn_gtw.setText("")
        self.label_back.setText("")
        self.label_credits.setText(QCoreApplication.translate("ComingSoon", u"Final project by : C2", None))
        self.label_4.setText(QCoreApplication.translate("ComingSoon", u"Next project here", None))
    # retranslateUi

